import { test, expect } from '@playwright/test';
test('crew CRUD, assignments and transparent optimization', async ({ page }) => {
  await page.goto('/crew');
  await expect(page.getByRole('heading', { name: 'Sarah Morgan', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '+ Add crew' }).click();
  await page.getByLabel('name', { exact: true }).fill('Smoke recruit');
  await page.getByRole('button', { name: 'Add skill' }).click();
  await page.getByLabel('Skill 1', { exact: true }).fill('Piloting');
  await page.getByRole('combobox', { name: 'Rank 1', exact: true }).selectOption('3');
  await page.getByRole('button', { name: 'Save crew' }).click();
  const card = page.getByRole('region', { name: 'Smoke recruit crew card' });
  await expect(card).toBeVisible();
  await card.getByRole('button', { name: 'Ship', exact: true }).click();
  await expect(card).toContainText('Ship / The Frontier');
  await card.getByRole('button', { name: 'Outpost', exact: true }).click();
  await expect(card).toContainText('Outpost / Luna Extraction Post');
  await page.getByLabel('Optimization goal').selectOption('outpost');
  await page.getByLabel('Available slots').fill('2');
  await page.getByRole('button', { name: 'Optimize crew' }).click();
  await expect(page.getByText('Highest total additive', { exact: false })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Lin', exact: true })).toHaveCount(2);
  await card.getByRole('button', { name: 'Edit Smoke recruit' }).click();
  await page.getByLabel('Crew notes').fill('Ready for deployment.');
  await page.getByRole('button', { name: 'Save crew' }).click();
  await card.getByRole('button', { name: 'Edit Smoke recruit' }).click();
  await expect(page.getByLabel('Crew notes')).toHaveValue('Ready for deployment.');
  await page.getByRole('button', { name: 'Delete crew', exact: true }).click();
  await page.getByRole('button', { name: 'Confirm delete crew' }).click();
  await expect(card).toHaveCount(0);
});
