import { test, expect } from '@playwright/test';
test('journal draft, mock generation, accept, save, edit, export and delete', async ({ page }) => {
  await page.goto('/journal/new');
  await page.getByLabel('Title', { exact: true }).fill('Smoke expedition');
  await page.getByLabel('Planet', { exact: true }).fill('Jemison');
  await page.getByLabel('Raw notes').fill('Landed safely. Collected survey readings.');
  await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem('starfield:log-draft:new'))?.title)).toBe('Smoke expedition');
  await page.reload();
  await expect(page.getByLabel('Title', { exact: true })).toHaveValue('Smoke expedition');
  await page.getByRole('button', { name: 'Generate Captain’s Log', exact: true }).click();
  await expect(page.getByLabel('Generated draft — review and edit')).toContainText('Landed safely');
  await page.getByRole('button', { name: 'Accept narrative' }).click();
  await page.getByRole('button', { name: 'Save log', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Smoke expedition' })).toBeVisible();
  const download = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export Markdown' }).click();
  expect((await download).suggestedFilename()).toMatch(/captains-log/);
  await page.getByRole('link', { name: 'Edit log' }).click();
  await page.getByLabel('Title', { exact: true }).fill('Smoke revised');
  await page.getByRole('button', { name: 'Save log', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Smoke revised' })).toBeVisible();
  await page.getByRole('button', { name: 'Delete', exact: true }).click();
  await page.getByRole('button', { name: 'Delete log', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Your story is waiting' })).toBeVisible();
});
test('map selection, pan, zoom, minimap, search and research remain available', async ({ page }) => {
  await page.goto('/');
  const map = page.getByRole('img', { name: /Interactive star map/ });
  const svg = page.locator('.star-map-svg');
  await expect(svg).toBeVisible();
  const initial = await svg.getAttribute('viewBox');
  await page.getByRole('button', { name: 'Zoom in', exact: true }).click();
  expect(await svg.getAttribute('viewBox')).not.toBe(initial);
  await page.getByRole('button', { name: 'Reset', exact: true }).click();
  await page.getByRole('combobox', { name: 'System search' }).fill('Sol');
  await page.getByRole('option', { name: /^Sol / }).click();
  await expect(page.locator('.selection-overlay')).toContainText('Sol');
  await page.goto('/ram');
  await expect(page.getByRole('heading', { name: 'Research & procurement' })).toBeVisible();
  await page.getByRole('button', { name: 'Pin', exact: true }).first().click();
  await page.reload();
  await expect(page.getByRole('button', { name: 'Unpin', exact: true })).toBeVisible();
  await expect(map).toHaveCount(0);
});
